### ISSUE TITLE
[Feature] 导入已有的番剧

### ISSUE THREAD

**Issue by TheresaQWQ** [ikaros-dev/ikaros#221]
### Search before asking

- [x] 我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### Description

如题，希望可以导入已有的资源，目前咱手头上有60G+的番，手动上传还是太折磨了（）

### Use case

扫描文件夹导入已有番剧

### Are you willing to submit a PR?

- [ ] 是的我想要提交个PR!

**Comment by li-guohao** [comment]
感谢你的issue，这个问题我们也在考虑中，考虑到技术实现难度、文件硬链接等多方面的因素，针对批量导入批量动漫，我们目前的初步方案是，不知道你觉得如何？

1. 用户把已有的动漫移动至 ikaros应用目录下的 original目录，ikaros会每个5分钟(或者后台主动点击执行这个任务)扫描下 original目录，将对应的动漫文件硬链接到文件管理
2. 用户在后台添加动漫
3. 用户在对应的动漫详情也关联资源
4. 用户将对应的动漫目录从 original目录移动到原来的目录

**Comment by li-guohao** [comment]
> 感谢你的issue，这个问题我们也在考虑中，考虑到技术实现难度、文件硬链接等多方面的因素，针对批量导入批量动漫，我们目前的初步方案是，不知道你觉得如何？
> 
> 1. 用户把已有的动漫移动至 ikaros应用目录下的 original目录，ikaros会每个5分钟(或者后台主动点击执行这个任务)扫描下 original目录，将对应的动漫文件硬链接到文件管理
> 2. 用户在后台添加动漫
> 3. 用户在对应的动漫详情也关联资源
> 4. 用户将对应的动漫目录从 original目录移动到原来的目录

优化后的方案步骤：
1. 用户启动时，添加一个媒体库映射目录，在容器里对应的目录则是应用目录下的 比如 storage 目录(不一定是这个名称)
2. 程序会定时扫描这个目录，先将目录移动到 original 目录，然后将对应的番剧剧集文件硬链接到文件管理目录(upload)，再将对应录入完的目录移动回去
3. 用户在后台添加动漫
4. 用户在对应的动漫详情页面关联资源

**Comment by li-guohao** [comment]
> > 感谢你的issue，这个问题我们也在考虑中，考虑到技术实现难度、文件硬链接等多方面的因素，针对批量导入批量动漫，我们目前的初步方案是，不知道你觉得如何？
> > 
> > 1. 用户把已有的动漫移动至 ikaros应用目录下的 original目录，ikaros会每个5分钟(或者后台主动点击执行这个任务)扫描下 original目录，将对应的动漫文件硬链接到文件管理
> > 2. 用户在后台添加动漫
> > 3. 用户在对应的动漫详情也关联资源
> > 4. 用户将对应的动漫目录从 original目录移动到原来的目录
> 
> 优化后的方案步骤(可行性待验证)：
> 
> 1. 用户启动时，添加一个媒体库映射目录，在容器里对应的目录则是应用目录下的 比如 storage 目录(不一定是这个名称)
> 2. 程序会定时扫描这个目录，先将这个目录下的目录移动到 original 目录，然后将对应的番剧剧集文件硬链接到文件管理目录(upload)，再将对应录入完的目录移动回去
> 3. 用户在后台添加动漫
> 4. 用户在对应的动漫详情页面关联资源

经过调试调整，最后在程序里的方案如下：
1. 用户启动时，添加一个已经存在的番剧的目录的映射，在容器里对应的目录则是应用目录下的 impoort 目录
2. 程序会定时扫描这个目录，先将对应的番剧剧集文件**复制**到文件管理目录(upload)
3. 用户在对应的动漫详情页面关联资源

**Comment by li-guohao** [comment]
> > 感谢你的issue，这个问题我们也在考虑中，考虑到技术实现难度、文件硬链接等多方面的因素，针对批量导入批量动漫，我们目前的初步方案是，不知道你觉得如何？
> > 
> > 1. 用户把已有的动漫移动至 ikaros应用目录下的 original目录，ikaros会每个5分钟(或者后台主动点击执行这个任务)扫描下 original目录，将对应的动漫文件硬链接到文件管理
> > 2. 用户在后台添加动漫
> > 3. 用户在对应的动漫详情也关联资源
> > 4. 用户将对应的动漫目录从 original目录移动到原来的目录
> 
> 优化后的方案步骤(可行性待验证)：
> 
> 1. 用户启动时，添加一个媒体库映射目录，在容器里对应的目录则是应用目录下的 比如 storage 目录(不一定是这个名称)
> 2. 程序会定时扫描这个目录，先将这个目录下的目录移动到 original 目录，然后将对应的番剧剧集文件硬链接到文件管理目录(upload)，再将对应录入完的目录移动回去
> 3. 用户在后台添加动漫
> 4. 用户在对应的动漫详情页面关联资源

经过调试调整，最后在程序里的方案如下：
1. 用户启动时，添加一个已经存在的番剧的目录的映射，在容器里对应的目录则是应用目录下的 impoort 目录
2. 程序会定时扫描这个目录，先将对应的番剧剧集文件**复制**到文件管理目录(upload)
3. 用户在对应的动漫详情页面关联资源
