### ISSUE TITLE
[Feature] 接口文档可以考虑使用 springdoc-openapi

### ISSUE THREAD

**Issue by nekolr** [ikaros-dev/ikaros#228]
### Search before asking

- [X] 我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### Description

see: https://github.com/springdoc/springdoc-openapi

### Are you willing to submit a PR?

- [ ] 是的我想要提交个PR!

**Comment by li-guohao** [comment]
目前使用的就是springdoc，但是他们还没有对Springboot3.0作支持，目前这部分配置类注释掉了
- https://github.com/ikaros-dev/ikaros/issues/197

**Comment by nekolr** [comment]
> 目前使用的就是springdoc，但是他们还没有对Springboot3.0作支持，目前这部分配置类注释掉了
> 
>     * [[Bug] Swagger UI的信息不正确 #197](https://github.com/ikaros-dev/ikaros/issues/197)
我提到的是： [springdoc-openapi](https://github.com/springdoc/springdoc-openapi)，不是 [springfox](https://github.com/springfox/springfox)，该组件已经很久没有维护了。

**Comment by li-guohao** [comment]
> > 目前使用的就是springdoc，但是他们还没有对Springboot3.0作支持，目前这部分配置类注释掉了
> > ```
> > * [[Bug] Swagger UI的信息不正确 #197](https://github.com/ikaros-dev/ikaros/issues/197)
> > ```
> 
> 我提到的是： [springdoc-openapi](https://github.com/springdoc/springdoc-openapi)，不是 [springfox](https://github.com/springfox/springfox)，该组件已经很久没有维护了。

我们会支持的，因为在 springboot3.0 springfox目前也无法使用，一个长期不更新维护的库如果有更好的选择，确实没有使用的必要。

**Comment by nekolr** [comment]
> > > 目前使用的就是springdoc，但是他们还没有对Springboot3.0作支持，目前这部分配置类注释掉了
> > > ```
> > > * [[Bug] Swagger UI的信息不正确 #197](https://github.com/ikaros-dev/ikaros/issues/197)
> > > ```
> > 
> > 
> > 我提到的是： [springdoc-openapi](https://github.com/springdoc/springdoc-openapi)，不是 [springfox](https://github.com/springfox/springfox)，该组件已经很久没有维护了。
> 
> 我们会支持的，因为在 springboot3.0 springfox目前也无法使用，一个长期不更新维护的库如果有更好的选择，确实没有使用的必要。

据我所知，很多项目都从 springfox 迁移到了 [springdoc-openapi](https://github.com/springdoc/springdoc-openapi)，该组件在 2.0.0 版本就已经支持 spring-boot 3.0.0 了

**Comment by li-guohao** [comment]
openapi组件使用springdoc不知道为啥一直404，等明天再看下。

**Comment by nekolr** [comment]
> openapi组件使用springdoc不知道为啥一直404，等明天再看下。

2.0.0 及以上版本才支持 spring-boot 3.0.0，see: https://github.com/springdoc/springdoc-openapi/releases/tag/v2.0.0

**Comment by li-guohao** [comment]
> > openapi组件使用springdoc不知道为啥一直404，等明天再看下。
> 
> 2.0.0 及以上版本才支持 spring-boot 3.0.0，see: https://github.com/springdoc/springdoc-openapi/releases/tag/v2.0.0

我好像找错文档了，还以为版本是1.6.4，里面的模块已经是2.0以上了，待会儿再试下
正确的文档链接：https://springdoc.org/v2/
