### ISSUE TITLE
[Bug] qb配置保存无法使用

### ISSUE THREAD

**Issue by TheresaQWQ** [ikaros-dev/ikaros#259]
### Search before asking

- [X] 我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### Ikaros Component

后端组件 (li-guohao/ikaros)

### What happened

![image](https://user-images.githubusercontent.com/22370654/209472155-ea1449fe-1607-416d-8e19-efd4ce5f7b26.png)
如图，浏览器请求这个接口直接就timeout

### What you expected to happen

能正常保存

### How to reproduce

- 首先给qb配置里面填写一个ikaros没法访问的ip（例如其他network中容器的ip）并保存，点击测试按钮
- 在ikaros保存好这个配置之后修改新配置就会出现无法保存，直接timeout

### Anything else

- 可以非常稳定的复现
- 完整日志内容如下

<details><summary>ikaros_server.log</summary>
ikaros_server    | org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://172.17.0.1:18080/api/v2/auth/login": Operation timed out
ikaros_server    |      at org.springframework.web.client.RestTemplate.createResourceAccessException(RestTemplate.java:888) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:868) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:405) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at run.ikaros.server.tripartite.qbittorrent.QbittorrentClient.getCookieByLogin(QbittorrentClient.java:130) ~[classes!/:na]
ikaros_server    |      at run.ikaros.server.tripartite.qbittorrent.QbittorrentClient.refreshHttpHeadersCookies(QbittorrentClient.java:93) ~[classes!/:na]
ikaros_server    |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
ikaros_server    |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
ikaros_server    |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
ikaros_server    |      at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
ikaros_server    |      at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.0.2.jar!/:6.0.2]ikaros_server    |      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752) ~[spring-aop-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:102) ~[spring-retry-2.0.0.jar!/:na]
ikaros_server    |      at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329) ~[spring-retry-2.0.0.jar!/:na]
ikaros_server    |      at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209) ~[spring-retry-2.0.0.jar!/:na]
ikaros_server    |      at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:135) ~[spring-retry-2.0.0.jar!/:na]
ikaros_server    |      at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:160) ~[spring-retry-2.0.0.jar!/:na]
ikaros_server    |      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.2.jar!/:6.0.2]ikaros_server    |      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752) ~[spring-aop-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703) ~[spring-aop-6.0.2.jar!/:6.0.2]
ikaros_server    |      at run.ikaros.server.tripartite.qbittorrent.QbittorrentClient$$SpringCGLIB$$0.refreshHttpHeadersCookies(<generated>) ~[classes!/:na]
ikaros_server    |      at run.ikaros.server.listener.QbittorrentOptionUpdateEventListener.onApplicationEvent(QbittorrentOptionUpdateEventListener.java:25) ~[classes!/:na]
ikaros_server    |      at run.ikaros.server.listener.QbittorrentOptionUpdateEventListener.onApplicationEvent(QbittorrentOptionUpdateEventListener.java:11) ~[classes!/:na]
ikaros_server    |      at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413) ~[spring-context-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370) ~[spring-context-6.0.2.jar!/:6.0.2]
ikaros_server    |      at run.ikaros.server.service.OptionServiceImpl.saveWithRequest(OptionServiceImpl.java:482) ~[classes!/:na]
ikaros_server    |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
ikaros_server    |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
ikaros_server    |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
ikaros_server    |      at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
ikaros_server    |      at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.0.2.jar!/:6.0.2]ikaros_server    |      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752) ~[spring-aop-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-6.0.2.jar!/:6.0.2]ikaros_server    |      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.2.jar!/:6.0.2]ikaros_server    |      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752) ~[spring-aop-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703) ~[spring-aop-6.0.2.jar!/:6.0.2]
ikaros_server    |      at run.ikaros.server.service.OptionServiceImpl$$SpringCGLIB$$0.saveWithRequest(<generated>) ~[classes!/:na]
ikaros_server    |      at run.ikaros.server.openapi.OptionRestController.saveOptionWithCategory(OptionRestController.java:88) ~[classes!/:na]
ikaros_server    |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
ikaros_server    |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
ikaros_server    |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
ikaros_server    |      at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
ikaros_server    |      at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1080) ~[spring-webmvc-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973) ~[spring-webmvc-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1003) ~[spring-webmvc-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:906) ~[spring-webmvc-6.0.2.jar!/:6.0.2]
ikaros_server    |      at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:731) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:880) ~[spring-webmvc-6.0.2.jar!/:6.0.2]
ikaros_server    |      at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:110) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:66) ~[spring-webmvc-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:365) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at run.ikaros.server.config.security.JwtAuthorizationFilter.doFilterInternal(JwtAuthorizationFilter.java:38) ~[classes!/:na]
ikaros_server    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.context.SecurityContextHolderFilter.doFilterInternal(SecurityContextHolderFilter.java:69) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191) ~[spring-security-web-6.0.0.jar!/:6.0.0]
ikaros_server    |      at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:351) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.2.jar!/:6.0.2]ikaros_server    |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:741) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1739) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.1.jar!/:na]
ikaros_server    |      at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
ikaros_server    | Caused by: java.net.ConnectException: Operation timed out
ikaros_server    |      at java.base/sun.nio.ch.Net.connect0(Native Method) ~[na:na]
ikaros_server    |      at java.base/sun.nio.ch.Net.connect(Net.java:579) ~[na:na]
ikaros_server    |      at java.base/sun.nio.ch.Net.connect(Net.java:568) ~[na:na]
ikaros_server    |      at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[na:na]
ikaros_server    |      at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
ikaros_server    |      at java.base/java.net.Socket.connect(Socket.java:583) ~[na:na]
ikaros_server    |      at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[na:na]
ikaros_server    |      at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531) ~[na:na]
ikaros_server    |      at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636) ~[na:na]
ikaros_server    |      at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:279) ~[na:na]
ikaros_server    |      at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:384) ~[na:na]
ikaros_server    |      at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:406) ~[na:na]
ikaros_server    |      at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309) ~[na:na]
ikaros_server    |      at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[na:na]
ikaros_server    |      at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[na:na]
ikaros_server    |      at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057) ~[na:na]
ikaros_server    |      at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:75) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:862) ~[spring-web-6.0.2.jar!/:6.0.2]
ikaros_server    |      ... 138 common frames omitted
ikaros_server    | 
ikaros_server    | 2022-12-25T22:46:43.892+08:00 DEBUG 1 --- [io-50000-exec-8] r.i.server.service.OptionServiceImpl     : publish QbittorrentOptionUpdateEvent
ikaros_server    | 2022-12-25T22:46:43.898+08:00 DEBUG 1 --- [o-50000-exec-10] r.i.server.service.OptionServiceImpl     : publish QbittorrentOptionUpdateEvent
ikaros_server    | 2022-12-25T22:46:43.903+08:00 DEBUG 1 --- [io-50000-exec-9] r.i.server.service.OptionServiceImpl     : publish QbittorrentOptionUpdateEvent
ikaros_server    | 2022-12-25T22:46:43.904+08:00 DEBUG 1 --- [o-50000-exec-10] s.l.QbittorrentOptionUpdateEventListener : receive QbittorrentOptionUpdateEvent
ikaros_server    | 2022-12-25T22:46:43.908+08:00 DEBUG 1 --- [io-50000-exec-9] s.l.QbittorrentOptionUpdateEventListener : receive QbittorrentOptionUpdateEvent
ikaros_database  | 2022-12-25 14:46:52.990 UTC [231] FATAL:  role "root" does not exist
ikaros_database  | 2022-12-25 14:47:03.312 UTC [238] FATAL:  role "root" does not exist
</details>

### Are you willing to submit PR?

- [ ] 是的我想要提交个PR!

**Comment by li-guohao** [comment]
感谢您的贡献，问题已经修复，
建议使用docker pull 重新拉取下 dev镜像
并重新up下您的docker compose yml文件
