### ISSUE TITLE
[Bug] 群辉docker部署容器角色

### ISSUE THREAD

**Issue by cosmos0715** [ikaros-dev/ikaros#533]
### 提问前查询

- [X] 我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### 组件

服务端 (server)

### 运行环境

群辉docker用Docker Compose进行部署（第一次部署正常运行，删除后更换硬盘部署出错）

### 报错相关的日志

```shell
2023/12/13 18:57:08	stderr	2023-12-13 10:57:08.191 UTC [5381] FATAL:  role "root" does not exist
2023/12/13 18:56:57	stderr	2023-12-13 10:56:57.775 UTC [5374] FATAL:  role "root" does not exist
2023/12/13 18:56:47	stderr	2023-12-13 10:56:47.397 UTC [5367] FATAL:  role "root" does not exist
2023/12/13 18:56:36	stderr	2023-12-13 10:56:36.860 UTC [5359] FATAL:  role "root" does not exist
2023/12/13 18:56:26	stderr	2023-12-13 10:56:26.522 UTC [5352] FATAL:  role "root" does not exist
2023/12/13 18:56:16	stderr	2023-12-13 10:56:16.130 UTC [5344] FATAL:  role "root" does not exist
2023/12/13 18:56:05	stderr	2023-12-13 10:56:05.777 UTC [5337] FATAL:  role "root" does not exist
2023/12/13 18:55:55	stderr	2023-12-13 10:55:55.392 UTC [5329] FATAL:  role "root" does not exist
2023/12/13 18:55:45	stderr	2023-12-13 10:55:45.055 UTC [5321] FATAL:  role "root" does not exist
2023/12/13 18:55:34	stderr	2023-12-13 10:55:34.505 UTC [5314] FATAL:  role "root" does not exist
2023/12/13 18:55:24	stderr	2023-12-13 10:55:24.168 UTC [5306] FATAL:  role "root" does not exist
2023/12/13 18:55:13	stderr	2023-12-13 10:55:13.857 UTC [5298] FATAL:  role "root" does not exist
2023/12/13 18:55:03	stderr	2023-12-13 10:55:03.397 UTC [5290] FATAL:  role "root" does not exist
2023/12/13 18:54:53	stderr	2023-12-13 10:54:53.076 UTC [5283] FATAL:  role "root" does not exist
2023/12/13 18:54:42	stderr	2023-12-13 10:54:42.722 UTC [5275] FATAL:  role "root" does not exist
2023/12/13 18:54:32	stderr	2023-12-13 10:54:32.356 UTC [5268] FATAL:  role "root" does not exist
2023/12/13 18:54:21	stderr	2023-12-13 10:54:21.937 UTC [5260] FATAL:  role "root" does not exist
```

### 发生了什么

ikaros_database容器一直报错
![屏幕截图 2023-12-13 162210](https://github.com/ikaros-dev/ikaros/assets/110033752/2bdf49cc-5cde-4a23-92a7-3a0e95be8567)

### 预期是怎样

如何正常运还行

### 如何复现

Docker Compose进行部署
``` yml
version: "3"
services:
    # ikaros
    ikaros:
        image: ikarosrun/ikaros:v0.11.7
        container_name: ikaros
        restart: on-failure:3
        depends_on:
          ikaros_database:
            condition: service_healthy
        networks:
          ikaros_networks:
        volumes:
          - ./:/root/.ikaros
        ports:
          - "9999:9999"
        healthcheck:
          test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
          interval: 30s
          timeout: 5s
          retries: 5
          start_period: 30s
        environment:
          # 避免中日文文件名称乱码，需要设置文件编码，先通过命令 [locale -a] 查询下宿主机编码，有的是 [C] 有的是 [zh_CN]，替换下方对应的字符
          - LANG=C.UTF-8
          - LANGUAGE=C:zh
          - LC_ALL=C.UTF-8
          - TZ=Asia/Shanghai
        command:
          - --logging.charset.console=UTF-8
          - --logging.charset.file=UTF-8
          # log level for package, such as INFO or DEBUG
          - --logging.level.run.ikaros.server=INFO
          - --logging.level.run.ikaros.plugin=INFO
          - --logging.level.run.ikaros.jellyfin=INFO
          - --sun.jnu.encoding=UTF-8
          - --spring.r2dbc.url=r2dbc:pool:postgresql://ikaros_database/ikaros
          - --spring.r2dbc.username=ikaros
          # PostgreSQL 的密码，请保证与下方 POSTGRES_PASSWORD 的变量值一致。
          - --spring.r2dbc.password=openpostgresql
          - --spring.sql.init.platform=postgresql
          # 初始化的超级管理员用户名
          - --ikaros.security.initializer.master-username=tomoki
          # 初始化的超级管理员密码
          - --ikaros.security.initializer.master-password=tomoki

    # ikaros database
    ikaros_database:
        image: postgres:latest
        container_name: ikaros_database
        restart: on-failure:3
        networks:
          ikaros_networks:
        volumes:
          - ./database:/var/lib/postgresql/data
        healthcheck:
          test: [ "CMD", "pg_isready" ]
          interval: 10s
          timeout: 5s
          retries: 5
        environment:
          - POSTGRES_DB=ikaros
          - POSTGRES_USER=ikaros
          - POSTGRES_PASSWORD=openpostgresql

networks:
  ikaros_networks:
    driver: bridge
```

### 其它补充内容

无其他补充内容

### 您将要去提交PR吗？

- [X] 是的我想要提交个PR!

**Comment by cosmos0715** [comment]
[ikaros_database.csv](https://github.com/ikaros-dev/ikaros/files/13659922/ikaros_database.csv)
日志文件

**Comment by li-guohao** [comment]
感谢贡献，请问 `ikaros`容器日志是否有异常？

**Comment by cosmos0715** [comment]
> 感谢贡献，请问 `ikaros`容器日志是否有异常？

重新部署之后ikaros网页端可以打开了，但是ikaros database容器日志依旧重复<html>
<body>

2023/12/13 19:44:33 | stderr | 2023-12-13 11:44:33.520 UTC [709] FATAL:  role "root" does not exist
-- | -- | --



</body>
</html>

**Comment by cosmos0715** [comment]
> > > 感谢贡献，请问 `ikaros`容器日志是否有异常？
> > 
> > 
> > 重新部署之后ikaros网页端可以打开了，但是ikaros database容器日志依旧重复
> > 2023/12/13 19:44:33 | stderr | 2023-12-13 11:44:33.520 UTC [709] FATAL:  role "root" does not exist -- | -- | --
> 
> 我没有群辉的环境可以用于测试， 估计这个问题还是在 `postgres`容器上的权限问题。 请问你是以什么用户执行 `docker-compose.yml` 文件的？如果不是`root`，建议使用`root`用户尝试下。 `ikaros`容器镜像目前还没有支持`PUID`和`PGID`，建议在NAS上使用`root`用户进行部署。

用的非root用户，可能是用户权限，不过我第一次成功部署也是用的非root用户

**Comment by cosmos0715** [comment]
> > > > 感谢贡献，请问 `ikaros`容器日志是否有异常？
> > > 
> > > 
> > > 重新部署之后ikaros网页端可以打开了，但是ikaros database容器日志依旧重复
> > > 2023/12/13 19:44:33 | stderr | 2023-12-13 11:44:33.520 UTC [709] FATAL:  role "root" does not exist -- | -- | --
> > 
> > 
> > 我没有群辉的环境可以用于测试， 估计这个问题还是在 `postgres`容器上的权限问题。 请问你是以什么用户执行 `docker-compose.yml` 文件的？如果不是`root`，建议使用`root`用户尝试下。 `ikaros`容器镜像目前还没有支持`PUID`和`PGID`，建议在NAS上使用`root`用户进行部署。
> 
> 用的非root用户，可能是用户权限，不过我第一次成功部署也是用的非root用户

目前已正常运行就不再重新部署了

**Comment by cosmos0715** [comment]
> > > > > 感谢贡献，请问 `ikaros`容器日志是否有异常？
> > > > 
> > > > 
> > > > 重新部署之后ikaros网页端可以打开了，但是ikaros database容器日志依旧重复
> > > > 2023/12/13 19:44:33 | stderr | 2023-12-13 11:44:33.520 UTC [709] FATAL:  role "root" does not exist -- | -- | --
> > > 
> > > 
> > > 我没有群辉的环境可以用于测试， 估计这个问题还是在 `postgres`容器上的权限问题。 请问你是以什么用户执行 `docker-compose.yml` 文件的？如果不是`root`，建议使用`root`用户尝试下。 `ikaros`容器镜像目前还没有支持`PUID`和`PGID`，建议在NAS上使用`root`用户进行部署。
> > 
> > 
> > 用的非root用户，可能是用户权限，不过我第一次成功部署也是用的非root用户
> 
> 目前已正常运行就不再重新部署了

另外plugin-mikan-0.11.0.jar插件上传报错 Plugin '/root/.ikaros/plugins/plugin-mikan-0.11.0.jar' already loaded with id 'PluginMikan'

**Comment by li-guohao** [comment]
> > > > > > 感谢贡献，请问 `ikaros`容器日志是否有异常？
> > > > > 
> > > > > 
> > > > > 重新部署之后ikaros网页端可以打开了，但是ikaros database容器日志依旧重复
> > > > > 2023/12/13 19:44:33 | stderr | 2023-12-13 11:44:33.520 UTC [709] FATAL:  role "root" does not exist -- | -- | --
> > > > 
> > > > 
> > > > 我没有群辉的环境可以用于测试， 估计这个问题还是在 `postgres`容器上的权限问题。 请问你是以什么用户执行 `docker-compose.yml` 文件的？如果不是`root`，建议使用`root`用户尝试下。 `ikaros`容器镜像目前还没有支持`PUID`和`PGID`，建议在NAS上使用`root`用户进行部署。
> > > 
> > > 
> > > 用的非root用户，可能是用户权限，不过我第一次成功部署也是用的非root用户
> > 
> > 
> > 目前已正常运行就不再重新部署了
> 
> 另外plugin-mikan-0.11.0.jar插件上传报错 Plugin '/root/.ikaros/plugins/plugin-mikan-0.11.0.jar' already loaded with id 'PluginMikan'

问题我已经收到，刚发下插件对应的 issue 那已经有人提了，我没收到邮件，才看到。
- https://github.com/ikaros-dev/plugin-mikan/issues/1
