### ISSUE TITLE
[Bug] 小说条目绑定资源提示非视频媒体

### ISSUE THREAD

**Issue by jerryyang-git** [ikaros-dev/ikaros#576]
### 提问前查询

- [X] 我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### 组件

控制台 (console)

### 运行环境

部署方式：docker
镜像版本：ikarosrun/ikaros:v0.12.0
插件：PluginBgmTv

### 报错相关的日志

```shell
请求参数异常: Matching fail, current attachment is not a video
```

### 发生了什么

我使用 BgmTv 插件添加了 ID 为 [38856](https://bgm.tv/subject/38856) 的条目，并确认条目类型为 `小说`
尝试绑定 EBUP 资源时提示 `请求参数异常: Matching fail, current attachment is not a video`

### 预期是怎样

小说格式当中，EBUP 属于较为常用格式

### 如何复现

使用 BgmTv 插件添加 ID 为 [38856](https://bgm.tv/subject/38856) 的条目，条目类型为 `小说`，点击绑定 EBUP小说资源
![录制_2024_06_16_21_27_05_987](https://github.com/ikaros-dev/ikaros/assets/60727068/c6c239c6-8b0e-4dd6-b428-c26fd7b69ab7)

### 您将要去提交PR吗？

- [ ] 是的我想要提交个PR!

**Comment by li-guohao** [comment]
请问是使用的那个批量绑定按钮吗？那个按钮目前基本只适配了番剧的视频绑定逻辑，这块后面需要优化，
建议目前先试试每个剧集的单个绑定按钮。

**Comment by li-guohao** [comment]
一个个绑定我自己都嫌烦，后面得尽快想办法优化。

**Comment by li-guohao** [comment]
刚用电脑看了下视频，没有剧集的情况下，就是是视频文件也会匹配失败。
需要先给条目创建个剧集，然后通过剧集的绑定按钮进行绑定。
附件是和剧集绑定的。

**Comment by li-guohao** [comment]
当条目没有剧集的时候，批量绑定这个按钮，需要加个禁用和提示。

可以考虑在条目新增时，检测到剧集没有条目，自动创建个默认的剧集条目。

**Comment by jerryyang-git** [comment]
> 刚用电脑看了下视频，没有剧集的情况下，就是是视频文件也会匹配失败。

对的，刚刚我尝试了下是可以成功绑定上

感觉小说这块的话，可以加个作者啊，出版社什么的数据类型好检索
然后给bgm添加个批量添加 ID 的功能，像游戏人生这样的系列小说，我直接收集好1-12部的 bgmID 一口气添加了

**Comment by li-guohao** [comment]
> > 刚用电脑看了下视频，没有剧集的情况下，就是是视频文件也会匹配失败。
> 
> 对的，刚刚我尝试了下是可以成功绑定上
> 
> 感觉小说这块的话，可以加个作者啊，出版社什么的数据类型好检索 然后给bgm添加个批量添加 ID 的功能，像游戏人生这样的系列小说，我直接收集好1-12部的 bgmID 一口气添加了

单独给类型加条件技术上没啥思路，不过已经有了全文检索的功能，那个`infobox`里的信息都在索引里，试试通过 `Cltr` + `/` 然后直接搜作者信息，应该是能找到条目的。

是指支持直接输入多个bgmId添加吗？那样的话输入的格式啥的，感觉也差不多的麻烦，bgmId一样得一个个去复制。

**Comment by li-guohao** [comment]
> 单独给类型加条件技术上没啥思路，不过已经有了全文检索的功能，那个infobox里的信息都在索引里，试试通过 Cltr + / 然后直接搜作者信息，应该是能找到条目的。


https://github.com/ikaros-dev/ikaros/assets/46225881/c5861a7f-9bed-4077-adc5-e3332c995541

**Comment by jerryyang-git** [comment]
> 试试通过 Cltr + / 然后直接搜作者信息，应该是能找到条目的。

原来还有这功能

**Comment by li-guohao** [comment]
> > 试试通过 Cltr + / 然后直接搜作者信息，应该是能找到条目的。
> 
> 原来还有这功能

这个是站内全文检索引擎，之前还支持搜一起附件的，就是搜个关键词，出来的结果有匹配的附件和条目，
但是附件的索引构建起来太耗时间了，就去掉了。

**Comment by jerryyang-git** [comment]
> bgmId一样得一个个去复制

感觉有api的话倒简单多，bgm是可以直接获取到系列下的所有关联条目的

![image](https://github.com/ikaros-dev/ikaros/assets/60727068/b829023e-157b-4e8f-a6e0-e7cae68052e0)

（要不书籍也像 bgm 一样搞成系列，然后包含单行本这样管理？（（

![image](https://github.com/ikaros-dev/ikaros/assets/60727068/634ba413-b9f3-4f49-978b-40e05235b7f8)


> 好像搜日文的效果不太好

目前的差不多也够用了，这个倒不用太过折腾，索引这一块折腾起来是一大坑

**Comment by li-guohao** [comment]
> > bgmId一样得一个个去复制
> 
> 感觉有api的话倒简单多，bgm是可以直接获取到系列下的所有关联条目的
> 
> ![image](https://private-user-images.githubusercontent.com/60727068/340110596-b829023e-157b-4e8f-a6e0-e7cae68052e0.png?jwt=XXX)
> 
> （要不书籍也像 bgm 一样搞成系列，然后包含单行本这样管理？（（
> 
> ![image](https://private-user-images.githubusercontent.com/60727068/340110855-634ba413-b9f3-4f49-978b-40e05235b7f8.png?jwt=XXX)
> 
> > 好像搜日文的效果不太好
> 
> 目前的差不多也够用了，这个倒不用太过折腾，索引这一块折腾起来是一大坑

这是什么JWT令牌，我先给你把评论删了，你重新评论下吧，令牌泄露不太好

**Comment by li-guohao** [comment]
直接批量添加所有条目相关的条目
这个可以做，但是需要交给插件去干。

而且本体关于条目匹配需要在列表页最好有个显示，当前条目下的剧集匹配进度，不然一下子加这么多条目，都不知道哪个自己已经配置了附件资源匹配，
比如按边框的颜色区分，是否已经匹配了资源

**Comment by jerryyang-git** [comment]
> 这是什么JWT令牌

没有填什么令牌，这个是 https://bangumi.github.io/api 好像直接进去就可以调试

> 直接批量添加所有条目相关的条目

一下子那么多有关联的条目进来确实有点……

> 按边框的颜色区分

按边框的颜色区分这种可以，我工作做过的所有公司 CRM 系统都是前面加个红色的 `新` 来区分有没有操作过，还挺直观的

**Comment by li-guohao** [comment]
小说附件的批量匹配，小说附件的文件名一般都是啥样的？是和番剧视频附件文件名一样的有 `01` `02`  `[01]` `[02]` 这种吗？

**Comment by jerryyang-git** [comment]
> 是和番剧视频附件文件名一样的有 `01` `02` `[01]` `[02]` 这种吗

emmm，这个感觉纯看个人爱好很杂乱，不过正常来说是 `系列名称 - 卷号 - 书名 - 作者`（我是这么管理的

即：我的游戏人生是这样的
![image](https://github.com/ikaros-dev/ikaros/assets/60727068/d43718a4-c90d-4ed6-999f-73725fa3073f)

**Comment by li-guohao** [comment]
> > 是和番剧视频附件文件名一样的有 `01` `02` `[01]` `[02]` 这种吗
> 
> emmm，这个感觉纯看个人爱好很杂乱，不过正常来说是 `系列名称 - 卷号 - 书名 - 作者[?版本]` 如果有特别版本或插图版，就后面加个`[?版本]`（我是这么管理的
> 
> 即：我的游戏人生是这样的 

目前批量匹配的规则只有文件名里包含 ` 01 ` 和 `[01]`这种，可以考虑加个 `-01-`这种的匹配规则。

**Comment by jerryyang-git** [comment]
> > > 是和番剧视频附件文件名一样的有 `01` `02` `[01]` `[02]` 这种吗
> > 
> > 
> > emmm，这个感觉纯看个人爱好很杂乱，不过正常来说是 `系列名称 - 卷号 - 书名 - 作者[?版本]` 如果有特别版本或插图版，就后面加个`[?版本]`（我是这么管理的
> > 即：我的游戏人生是这样的
> 
> 目前批量匹配的规则只有文件名里包含 `01` 和 `[01]`这种，可以考虑加个 `-01-`这种的匹配规则。

嗯，除了这些 `01` `[01]` `-01-` `_01_`，感觉还可以考虑加个`[CN]` `[EN]` `[JP]`或者 `[特典]` 什么的？

**Comment by li-guohao** [comment]
> -01-

批量匹配只负责匹配附件对应剧集的序号，其它的不匹配。

**Comment by li-guohao** [comment]
可以试试 `v0.12.2`的版本
