### ISSUE TITLE
[Bug] 单个剧集绑定多资源无法正常显示

### ISSUE THREAD

**Issue by jerryyang-git** [ikaros-dev/ikaros#593]
### 提问前查询

- [X] 我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### 组件

控制台 (console)

### 运行环境

部署方式：docker；版本：0.12.6

### 发生了什么

我使用BGM_TV插件同步了BGMID为13的条目，剧集绑定资源时只显示单个资源，多个资源无法显示
下方是api返回与后台显示界面
![image](https://github.com/ikaros-dev/ikaros/assets/60727068/2a4ee698-cf73-401e-9bff-65aefa6afb02)

![image](https://github.com/ikaros-dev/ikaros/assets/60727068/786c076f-8c27-4e2a-a5f4-1b91322331c9)

### 预期是怎样

`/console` 页面可以列出剧集绑定的多个资源

### 如何复现

绑定多个资源
![image](https://github.com/ikaros-dev/ikaros/assets/60727068/bf119cb4-ad12-4e56-9277-bf0db033b9d0)

**Comment by chivehao** [comment]
剧集详情页后续不预览附件了，直接改成多个附件卡片，可以点击附件卡片直接跳转到对应的附件目录。

**Comment by chivehao** [comment]
> 剧集详情页后续不预览附件了，直接改成多个附件卡片，可以点击附件卡片直接跳转到对应的附件目录。

最终修复是根据资源数目和类型，自动判断预览类型：


https://github.com/ikaros-dev/ikaros/assets/46225881/673f755b-0ca9-47e4-962f-e01375f842db
