### ISSUE TITLE
[Bug] 优化 console 界面标签的输入和检索功能

### ISSUE THREAD

**Issue by jerryyang-git** [ikaros-dev/ikaros#596]
### 创建前查询

- [X] 我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### 描述

在添加条目 `标签` 输入完成后需要鼠标点击其他地方使其失去焦点才能添加，且在下一次添加时输入框还是会保留上一次输入的值

可以改进下操作逻辑
当用户输入完标签后，按下回车键可以立即添加标签，并且输入框自动清空，方便用户连续输入下一个标签。

### 使用案例

可以参考 Tyepcho 的标签逻辑

https://github.com/ikaros-dev/ikaros/assets/60727068/e864bcea-de0f-4171-bfbf-2a95531aedf2

**Comment by chivehao** [comment]
标签其实目前没啥用，只是为了后续做准备预留的。

**Comment by chivehao** [comment]
额，看了下代码，这小问题，我顺手在0.13修了。
