### ISSUE TITLE
[Bug] 编辑条目界面多条绑定资源显示不全

### ISSUE THREAD

**Issue by jerryyang-git** [ikaros-dev/ikaros#604]
### 提问前查询

- [X] 我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### 组件

控制台 (console)

### 运行环境

部署方式：docker，版本：v0.13.0

### 发生了什么

条目编辑界面文件绑定显示不全
![image](https://github.com/ikaros-dev/ikaros/assets/60727068/80281c88-16a0-4008-9351-46ec07d49aa0)

### 预期是怎样

预期应该与条目详情页一样
![image](https://github.com/ikaros-dev/ikaros/assets/60727068/97fa5580-b95c-484d-b41e-54c3c513c2c5)

### 如何复现

编辑条目——点击剧集详情/编辑

### 其它补充内容

#593 

### 您将要去提交PR吗？

- [ ] 是的我想要提交个PR!

**Comment by chivehao** [comment]
> 好像是重复的代码没抽取出来，只改了一处。

条目编辑页的剧集详情对话框，入参没改过来，`v0.13.1`短时间内不会发布，可以先用`dev`的docker tag，这个tag每次PR合并都会覆盖更新。

**Comment by jerryyang-git** [comment]
> 可以先用`dev`的docker tag

好的
