### ISSUE TITLE
[Feature] indices api 添加 cover 字段

### ISSUE THREAD

**Issue by jerryyang-git** [ikaros-dev/ikaros#607]
### 创建前查询

- [X] 我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### 描述

搜索结果可以添加个 cover 图片字段，感觉搜索结果有图片封面会好点

### 您想要提交PR吗?

- [ ] 是的我想要提交个PR!

**Comment by chivehao** [comment]
接口会有，但是目前后台console的全局搜索页面暂时不加了。
