### ISSUE TITLE
[Bug] 条目关系查询 API 404 返回格式不是标准 JSON

### ISSUE THREAD

**Issue by jerryyang-git** [ikaros-dev/ikaros#609]
### 提问前查询

- [X] 我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### 组件

服务端 (server)

### 运行环境

部署方式：Docker
版本：0.13.0

### 发生了什么

![image](https://github.com/ikaros-dev/ikaros/assets/60727068/274f982b-196e-4dbc-89ac-719e99e0cf6e)

返回的内容不是正常的 JSON

![image](https://github.com/ikaros-dev/ikaros/assets/60727068/75ccc4f8-1bd8-436f-83fc-13cd81cb3c18)

### 预期是怎样

{
    "messages":"Not found for subject id: 247785"
}

### 如何复现

使用 `/api/v1alpha1/subject/relations` api

### 您将要去提交PR吗？

- [ ] 是的我想要提交个PR!

**Comment by chivehao** [comment]
这个问题修复后会返回200和空数据
