### ISSUE TITLE
[Feature] 针对不同尺寸图片的显示优化

### ISSUE THREAD

**Issue by dunquzhiyi** [ikaros-dev/ikaros#628]
### 创建前查询

- [X] 我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### 描述

当前封面的展示区域更适合heigth>width的情形,当图片趋近于正方形或者height<width时，留白较大。
希望可以优化显示区域的大小，提供图片裁剪等功能。

**Comment by chivehao** [comment]
条目图片显示的宽高比不好修改，
但裁剪功能可以做。

**Comment by chivehao** [comment]
v0.14.1更新了，升级后，在条目编辑页进行裁剪，根据已经存在的封面进行裁剪。
文档目前没空更新，好像还在0.13。
