### ISSUE TITLE
[Bug] 电脑本地上传附件到nas服务器端会卡到一半不动

### ISSUE THREAD

**Issue by gsxgmpkt9020** [ikaros-dev/ikaros#743]
### 提问前查询

- [X] 我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### 组件

服务端 (server)

### 运行环境

Git Branch	HEAD	Git Commit	f340701	Commit Time	2024-11-24
Build Version	0.20.6	Build Name	server	Build Time	2024-11-24
OS Name	Linux	OS Version	4.4.302+	OS Arch	aarch64

Java Version | 17.0.12 | Vendor Name | Eclipse Adoptium | Vendor Version | Temurin-17.0.12+7
-- | -- | -- | -- | -- | --
Runtime Name | OpenJDK Runtime Environment | Runtime Version | 17.0.12+7
JVM Name | OpenJDK 64-Bit Server VM | JVM Vendor | Eclipse Adoptium | JVM Version | 17.0.12+7

POSTGRESQL 13.2-3

### 报错相关的日志

```shell
A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

### 发生了什么

上传附件卡住

![20241204213009003](https://github.com/user-attachments/assets/b4ed8b3f-7187-409d-9fd8-0b737216dad5)
![20241204213100004](https://github.com/user-attachments/assets/b7803818-5ce3-4d43-bcdc-d3575a07352e)

### 预期是怎样

上传附件成功

### 如何复现

正常操作上传附件

**Comment by chivehao** [comment]
请问是每次上传都会卡住嘛？

**Comment by chivehao** [comment]
> 低端配置。
> 
> 我的想法是对于这种低端服务器用群晖上传工具把数据放进links文件夹（更有鲁棒性），然后让plugin-local-files-import把数据吞进去作为普通上传的替代。
> 
> ```
> CPU Realtek RTD1296 四核心 1.4GHz
> 硬體加密引擎 有
> 硬體轉碼引擎
> • 支援轉碼器：MPEG-4 Part 2 (XVID, DIVX5)、MPEG-2、VC-1、10-bit H.265 (HEVC)
> • 最高解析度：4K (4096 x 2160)
> • 每秒最大幀率 (FPS)：60
> 記憶體 1 GB DDR4
> 相容硬碟類型 2 x 3.5 吋或 2.5 吋 S
> ```

才1GB的内存嘛？我怀疑是内存太少了，你肯定还有其它软件，安装完ikaros后，剩余内存还剩多少？

**Comment by chivehao** [comment]
> 已经确认大概率是chrome 浏览器的性能bug或受其第三方扩展影响
> 
> 参考Version 131.0.6778.87，或许建个新profile就行了。
> 
> 抛弃了臃肿的chrome，用fresh new的firefox上传可靠性杠杠的

你本地部署的服务端用这个版本chrome 能正常上传吗？
