### ISSUE TITLE
[Feature]  增加给剧集条目质量打分的功能

### ISSUE THREAD

**Issue by gsxgmpkt9020** [ikaros-dev/ikaros#744]
### 创建前查询

- [X] 我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### 描述

增加给剧集条目质量打分的功能

### 使用案例

给条目打分,方便未来对条目的排序筛选和管理

**Comment by chivehao** [comment]
剧集评分和条目评分？

关于排序的话，目前有用app吗？app 那块已经支持多条件排序了，console 这块我还没弄高级筛选。

- [ ] 条目评分
- [ ] 剧集评分
- [ ] 条目筛选需要添加按评分排序`最高评分`

**Comment by chivehao** [comment]
话说需要给剧集进行打分嘛？

**Comment by chivehao** [comment]
> > 话说需要给剧集进行打分嘛？我咋感觉没啥必要。
> 
> 1. 想当于favourite的一个细分，空间不够了我会优先把低分的视频删除。
> 2. 重新回顾老番的时候有一个优先级层级感
> 3. 影音媒体库比较典型的就是有rating栏。
> 4. 可以做成插件节省资源开销
> 
> ![image](https://github.com/user-attachments/assets/e4049a8f-4ef3-4ed5-8931-c97d1c36ef6a)
> 

那感觉这和剧集也没啥关系，有关系也是附件那块，感觉不是很有必要给附件一个评分。

**Comment by chivehao** [comment]
> > 话说需要给剧集进行打分嘛？我咋感觉没啥必要。
> 
> 1. 想当于favourite的一个细分，空间不够了我会优先把低分的视频删除。
> 2. 重新回顾老番的时候有一个优先级层级感
> 3. 影音媒体库比较典型的就是有rating栏。
> 4. 可以做成插件节省资源开销
> 
> ![image](https://github.com/user-attachments/assets/e4049a8f-4ef3-4ed5-8931-c97d1c36ef6a)
> 

有没有更具体点的使用场景举例？

**Comment by chivehao** [comment]
> 1. 最简单的就是辅助排序筛选定位了。比如有一万个资源，但我不记得名字
> 2. 如果以后出tag功能的话，也能勉强替代吧
> 3.老实说我的番剧目录就是按照评分区间建立的。我也可以照样沿用我的，比如99-95分为一个目录，作为评分的替代

不用那么麻烦，目前ikaros条目已经加到了全局索引里，直接搜关键词即可，无论是标签还是描述还是制作组，只要和条目相关，都能搜索出来。
console 打开全局搜索是按键盘 Ctrl + / .
app条目列表页右上角那个放大镜

**Comment by chivehao** [comment]
> BGM插件提了个issue，帮我看下

那边我之前没开仓库的`Ubwatch All activity`，收不到issue邮件，目前已经开了。
