### ISSUE TITLE
[Bug] Qbittorrent通过URL下载Torrent会出现丢失文件问题

### ISSUE THREAD

**Issue by chivehao** [ikaros-dev/ikaros#87]
### Search before asking

- [X] 我已经在 [issues](https://github.com/li-guohao/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### Ikaros Component

后端组件 (li-guohao/ikaros)

### What happened

Qbittorrent通过URL下载Torrent会出现丢失文件问题，经推测是由于Qbittorrent下载种子文件失败或者太慢了导致的

### What you expected to happen

能正常添加下载torrent

### Are you willing to submit PR?

- [X] 是的我想要提交个PR!

**Comment by li-guohao** [comment]
解决方案，Ikaros通过代理把torrent文件下载到 /path/to/app/downloads/temp/ 目录下，
调用qbittorrent web api 直接添加本地的torrent文件

**Comment by li-guohao** [comment]
我先尝试批量添加一次

**Comment by li-guohao** [comment]
已解决
